# Generated by Django 4.1.7 on 2023-03-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_publsiher_post_publisher_rename_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
